### ISSUE TITLE
Installer script failes on downloading

### ISSUE THREAD

**Issue by KarfiolosHus** [DravenusRex/stalker-gamma-linux-guide#20]
**System information**

Operating system: Linux Mint 21.2 Cinnamon
Env version : 5.8.4
Kernel: 5.15.0-91-generic
Proc: Intel© Core™ i5-6500 CPU @ 3.20GHz × 4
GPU: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
RAM: 7.7 GiB

**Description**

After downloading and extracting the required file to their designated Anomaly and GAMMA folders, the installer script fails on downloading The Combat Behavior mod.

`[+] Installing mod:  Xenotech Protects Cordon Base
  - Downloading Combat_Behavior_1.02.4.rar: 28.8kiB [00:00, 168kiB/s]
Traceback (most recent call last):
  File "/path/gamma-launcher-master/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
  File "/path/gamma-launcher-master/env/lib/python3.10/site-packages/launcher/cli.py", line 70, in main
    args.cobject().run(args)
  File "/path/gamma-launcher-master/env/lib/python3.10/site-packages/launcher/commands/install.py", line 414, in run
    self._install_mods()
  File "/path/gamma-launcher-master/env/lib/python3.10/site-packages/launcher/commands/install.py", line 365, in _install_mods
    self._install_mod(k, v)
  File "/path/gamma-launcher-master/env/lib/python3.10/site-packages/launcher/commands/install.py", line 331, in _install_mod
    extract_archive(file, dir)
  File "/path/gamma-launcher-master/env/lib/python3.10/site-packages/launcher/archive.py", line 57, in extract_archive
    _extract_func_dict.get(ext)(filename, path)
  File "/path/gamma-launcher-master/env/lib/python3.10/site-packages/launcher/archive.py", line 49, in <lambda>
    'rar': lambda f, p: RarFile(f).extractall(p),
  File "/path/gamma-launcher-master/env/lib/python3.10/site-packages/rarfile.py", line 875, in extractall
    dst = self._extract_one(inf, path, pwd, not inf.is_dir())
  File "/path/gamma-launcher-master/env/lib/python3.10/site-packages/rarfile.py", line 940, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
  File "/path/gamma-launcher-master/env/lib/python3.10/site-packages/rarfile.py", line 955, in _make_file
    shutil.copyfileobj(src, dst)
  File "/usr/lib/python3.10/shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "/path/gamma-launcher-master/env/lib/python3.10/site-packages/rarfile.py", line 2284, in read
    raise BadRarFile("Failed the read enough data: req=%d got=%d" % (orig, len(data)))
rarfile.BadRarFile: Failed the read enough data: req=3178 got=124`

**Things I've tried so far:**

- Download the mod separately, so maybe the script would skip at, but still fails.

**Comment by Mord3rca** [comment]
Hello, are you using `unrar` free ?
It is not supported yet by rarfile: https://github.com/Mord3rca/gamma-launcher/issues/65
You should install this one: https://community.linuxmint.com/software/view/unrar

**Comment by KarfiolosHus** [comment]
It fixed the issue, thanks. Now there are some mode which the script could parse. I'm closing the issue.
