### ISSUE TITLE
After install, Mod Organizer refuses to start

### ISSUE THREAD

**Issue by stubkan** [DravenusRex/stalker-gamma-linux-guide#21]
Using Heroic Launcher as frontend to launch.  Ubuntu system.

Starting Anomaly works great, can load a world with no problems.

Have reinstalled the whole thing 3 times, once only using Mord3rca's launcher to install, and every time it fails, because Mod Organizer fails to start, after selecting C:/Anomaly as the game folder as per the instructions, it immediately stops with this issue

```
Cannot launch program - Cannot start

This error typically happens because an antivirus has deleted critical files from Mod Organizer's installation folder or has made them generally inaccessible.  Add an exclusion for Mod Organizer's installation folder in your antivirus, reinstall Mod Organizer and try again.

> details
Error 87 ERROR_INVALID_PARAMETER: Invalidparameter. (0x57)
 . binary: ''
 . owner: (file not found)
 . rights: (file not found)
 . arguments: ''
 . cwd: 'C:\GAMMA'
 . stdout: no, stderr: no, hooked: yes
 . MO elevated: yes
 . usvfs x86:ok x64:ok proxy_x86:ok proxy_x64:ok
 ```
 
Anomaly fails to verify every time I try --check - with files failing.  Error output doesnt seem helpful as, they are all the right files that were put there by the install.

```
Checking Anomaly file: /home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/db/textures/textures_weapons.db1...: 100%|#| 514M/514M [00:01<
Checking Anomaly file: /home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/db/textures/textures_weapons.db2...: 100%|#| 272M/272M [00:00<
Checking Anomaly file: /home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/db/files.db0...: 100%|#####| 381k/381k [00:00<00:00, 327MiB/s]
Checking Anomaly file: /home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/db/shaders.db0...: 100%|###| 914k/914k [00:00<00:00, 413MiB/s]
Traceback (most recent call last):
  File "gamma-launcher.py", line 8, in <module>
  File "launcher/cli.py", line 68, in main
  File "launcher/commands/check.py", line 44, in run
RuntimeError: Invalid file(s) detected:
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/bin/AnomalyDX10.exe
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/bin/AnomalyDX10AVX.exe
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/bin/AnomalyDX11.exe
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/bin/AnomalyDX11AVX.exe
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/bin/AnomalyDX8.exe
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/bin/AnomalyDX8AVX.exe
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/bin/AnomalyDX9.exe
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/bin/AnomalyDX9AVX.exe
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/bin/soft_oal.dll
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/db/configs/configs.db0
/home/stubkan/DriveTwo/Stalker/drive_c/Anomaly/db/configs/scripts.db0
[179419] Failed to execute script 'gamma-launcher' due to unhandled exception!
```
winetricks installed
```
wine-8.19 (Staging) and WINEARCH=win64
cmd
d3dcompiler_47
d3dx10
d3dx11_43
d3dx9
dx8vb
d3dcompiler_43
d3dx9
d3dcompiler_47
dxvk
quartz
w_workaround_wine_bug-50894
ucrtbase2019
vcrun2019
```

**Comment by stubkan** [comment]
It seems to be related to paths and permissions.  I attempted to re-do the process by picking a path via system path Z: instead of the prefix emulated path C: and noticed the stalker directory was missing, having been removed from the systems path

So I moved Anomaly folder outside the prefix's C:/Anomaly into linux system and suddenly the mod organizer starts straight away.

I swap it around so Anomaly is back in C:/Anomaly but GAMMA is outside in linux system, I have no idea which should be inside, or if both should be outside ..  Anyway, it starts Mod Organizer and 442 mods are listed - I suspect this is another issue, for another discussion.

The game launcher starts now, and I click to start the game - but it never starts, just a black box pops up, then disappears.  Rather disappointing.  I closed down Heroic Launcher, and did some more research, to try to figure out other ideas.  Restarted Heroic, now Mod Organizer 2 won't start at all, no error popups, nothing.  

This stuff is quite frustrating.
